name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Build Docker image
        run: docker build -t my-app:latest .
      
      - name: Run Unit Tests
        run: |
          docker run --rm my-app:latest npm test
